<a href="https://colab.research.google.com/github/Varalakshmi-skab/datasciencelearning/blob/main/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###EDA => Exploratory data analysis


* It is the process of understanding and analysis data before building models
----
---> We need to check👇
*   Is there any missing values?
*   Is there any duplicates?
*   What patterns exist?
*   What columns are importent?
*   Is the data set is balanced or not?
----
--->Without EDA😥👇👇

*   we may train model on wrong data!!
*   Missing values create errors!!
*   Outlies can redure Accuracy!!
-->1,2,3,4,5,45,6,6,10,30,40,1000

In [2]:
#step 1 : import libraries

In [3]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [4]:
#dataset loading
df = sns.load_dataset('titanic')

In [5]:
#view dataset
df.head() #shows first 5 rows

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.tail() #shows last 5 rows

In [16]:
df.sample()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
411,0,3,male,NaN,0,0,6.8583,Q,Third,man,True,NaN,Queenstown,no,True

#understanding dataset structure

In [ ]:
df.shape #it will tell how manys rows and columns

In [ ]:
df.columns #it will tell what are the columns

In [ ]:
#shows datatypes, non null values , datatype
df.info()

In [ ]:
df.dtypes #showing dtypes

#statistical summary or descriptive summary
*   mean
*   median
*   max
*   Variance

In [ ]:
df.describe() #statiscal summary

-->we have to check missing values

In [ ]:
df.isnull()

In [ ]:
df.isnull().sum()


--> we have to fill the values using **fillna** method (mean,mode,median,logic)

--> we have to delete the rows and columns by using **drop**

-->we have to check duplicate records

In [ ]:
df.duplicated().sum()

--> if we have duplicate records just we will those using **drop**

#correlation analysis
--> next we have to find correlations

In [ ]:
df.corr(numeric_only=True)

--> we need to find ***outlies\*** : we use **Visualization** for that

-->check dataset balanced or imbalanced

-->feature engineering

#All these process is called EDA
->dataset reading

->info

->stat analysis

->missing values

->filling missingdrop

->duplicates

->correleation

->outlierrs

->feature engineering

->balance checking