<a href="https://colab.research.google.com/github/Varalakshmi-skab/datasciencelearning/blob/main/K_NN_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [27]:
df=pd.read_csv("/content/drive/MyDrive/Datasets for datascience/knnclassification.csv")
df.head()

   ApplicantIncome  CreditScore  ...  ExistingLoans  Loan_Status
0            61907          739  ...              1     Approved
1            25495          521  ...              4     Rejected
2            98010          798  ...              0     Approved
3           101378          657  ...              1     Approved
4            73393          710  ...              1     Approved

[5 rows x 6 columns]

In [28]:
df.columns

Index(['ApplicantIncome', 'CreditScore', 'LoanAmount', 'EmploymentYears',
       'ExistingLoans', 'Loan_Status'],
      dtype='object')

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ApplicantIncome  5000 non-null   int64
 1   CreditScore      5000 non-null   int64
 2   LoanAmount       5000 non-null   int64
 3   EmploymentYears  5000 non-null   int64
 4   ExistingLoans    5000 non-null   int64
 5   Loan_Status      5000 non-null   object
dtypes: int64(5), object(1)
memory usage: 234.5+ KB

In [30]:
df.isnull().sum()

ApplicantIncome    0
CreditScore        0
LoanAmount         0
EmploymentYears    0
ExistingLoans      0
Loan_Status        0
dtype: int64

In [31]:
df.duplicated().sum()

np.int64(0)

In [32]:
X=df.drop("Loan_Status",axis=1)
X
Y=df["Loan_Status"]

In [33]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(4000, 5)
(1000, 5)
(4000,)
(1000,)

In [34]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
X_train=scalar.fit_transform(X_train)
X_test=scalar.transform(X_test)

In [35]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,Y_train)

KNeighborsClassifier()

In [36]:
y_pred=knn.predict(X_test)

In [37]:
confusion_matrix=confusion_matrix(Y_test,y_pred)
print(confusion_matrix)
accuracy_score=accuracy_score(Y_test,y_pred)
print(accuracy_score)
precision_score=precision_score(Y_test,y_pred,pos_label="Approved")
print(precision_score)
recall_score=recall_score(Y_test,y_pred,pos_label="Approved")
print(recall_score)
f1_score=f1_score(Y_test,y_pred,pos_label="Approved")
print(f1_score)

[[500   1]
 [  0 499]]
0.999
1.0
0.998003992015968
0.999000999000999